#!/usr/local/bin/python3.6
from random import randint
from string import ascii_letters
import hashlib


def generate_random_string(characters_length=20):
    password = ''

    for i in range(characters_length):
        password += str(ascii_letters[randint(0, len(ascii_letters) - 1)])

    return password


def generate_md5_hash(random_string):
    return hashlib.md5(random_string.encode('utf-8')).hexdigest()


def configure_phpmyadmin():
    """
    Configures phpMyAdmin configuration
        1) Copies config.sample.inc.php to config.inc.php
        2) Sets blowfish_secret passphrase
    """

    with open('/usr/share/phpMyAdmin/config.sample.inc.php', 'r') as source:
        data = source.read()

    data = data.replace("$cfg['blowfish_secret'] = ''; /* YOU MUST FILL IN THIS FOR COOKIE AUTH! */",
                  "$cfg['blowfish_secret'] = '" + generate_md5_hash(generate_random_string(100)) + "'; /* "
                  "Generated by configure.py */")

    with open('/usr/share/phpMyAdmin/config.inc.php', 'w') as destination:
        destination.write(data)


"""
Run necessary functions
"""
print('phpMyAdmin => Sets blowfish_secret passphrase...')
configure_phpmyadmin()
